name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: fastapi-hello
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: my-cluster
      GKE_ZONE: europe-west1
      DEPLOYMENT_NAME: fastapi-deployment

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
         project_id:  ${{ secrets.GCP_PROJECT_ID }}
         service_account_key: ${{ secrets.GCP_CREDENTIALS }}
         export_default_credentials: true

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io

    - name: Build, Tag, and Push Docker image
      run: |
        IMAGE_TAG="gcr.io/soy-beaker-451600-p5/fastapi-hello/demo:latest"
        echo "Using image tag: $IMAGE_TAG"
        docker build -t "$IMAGE_TAG" .
       
        docker push "$IMAGE_TAG"

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl set image deployment/$DEPLOYMENT_NAME fastapi-container=gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest

