name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: my-cluster
  GKE_ZONE: europe-west1
  DEPLOYMENT_NAME: fastapi-deployment
  IMAGE_NAME: fastapi-hello

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io

    - name: Build, Tag, and Push Docker image
      run: |
        # Build Docker image locally
        docker build -t $IMAGE_NAME .

        # Correctly tag the Docker image for GCR
        docker tag $IMAGE_NAME gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

        # Push Docker image to GCR
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --region $GKE_ZONE

    - name: Deploy to GKE
      run: |
        kubectl apply -f deployment.yaml
        kubectl set image deployment/$DEPLOYMENT_NAME fastapi-container=gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

